Repository kolide/fleet, pull requests merged in 2018-06, with the labels that each got.

#1803 Update frontend dependencies
  frontend/components/Avatar/Avatar.tsx
  frontend/components/buttons/Button/Button.tsx
  package.json
  tsconfig.json
  tslint.json
  yarn.lock
Labels: Component: Frontend, Component: Technical Debt, Needs: Review

#1806 Last Seen date and time on Offline host cards and table overview
  frontend/components/hosts/HostDetails/HostDetails.jsx
  frontend/components/hosts/HostDetails/helpers.js
  frontend/components/hosts/HostsTable/HostsTable.jsx
Labels: Component: Frontend, Needs: Review

#1830 Fix labels UI errors in Fleet 2.0
  server/datastore/datastore_labels_test.go
  server/datastore/datastore_test.go
  server/datastore/mysql/labels.go
  server/kolide/labels.go
  server/mock/datastore_labels.go
  server/service/endpoint_labels.go
  server/service/handler.go
  server/service/logging_labels.go
  server/service/metrics_labels.go
  server/service/service_labels.go
  server/service/transport_labels.go
  server/service/transport_labels_test.go
Labels: Bug

#1834 Update changelog for Fleet 2.0 RC2 release
  CHANGELOG.md
Labels: Component: Documentation

#1841 Fix All Hosts label in docs
  docs/cli/file-format.md
Labels: Component: Documentation

#1842 Fix deletion of queries referenced by foreign key
  server/datastore/datastore_scheduled_queries_test.go
  server/datastore/datastore_test.go
  server/datastore/mysql/migrations/tables/20180620164811_PackAndQueryDeletion.go
Labels: Bug, Component: Databases, Feature: Packs, Feature: Queries

#1843 Fix bugs with packs created in UI
  server/datastore/datastore_packs_test.go
  server/datastore/datastore_queries_test.go
  server/datastore/mysql/migrations/tables/20180620175054_ScheduledQueryNameKeys.go
  server/datastore/mysql/scheduled_queries.go
  server/kolide/scheduled_queries.go
  server/service/endpoint_scheduled_queries.go
  server/service/service_scheduled_queries.go
Labels: Bug

#1848 Fix deletion of labels in UI
  frontend/kolide/entities/labels.js
  frontend/kolide/entities/queries.js
  frontend/test/mocks/label_mocks.js
  server/kolide/labels.go
  server/service/endpoint_labels.go
  server/service/handler.go
  server/service/service_labels.go
  server/service/transport_labels.go
Labels: Bug, Component: Frontend, Feature: Labels

#1851 Fix error when migrating packs and scheduled query has been deleted.
  server/datastore/mysql/migrations/tables/20171219164727_UpdateScheduledQueryKey.go
Labels: Bug, Component: Databases

#1855 Fix errors and clarify docs on config platform overrides
  docs/cli/file-format.md
  examples/config-many-files/config.yml
  examples/config-single-file.yml
Labels: Component: Documentation

#1856 Fix newline handling in fleetctl convert
  cmd/fleetctl/convert.go
Labels: Bug, Feature: CLI
