Repository kolide/fleet, pull requests merged in 2018-05, with the labels that each got.

#1753 Update changelog for 1.0.8 release
  CHANGELOG.md
Labels: Component: Documentation

#1760 Implement clients for labels, packs and queries
  server/service/client.go
  server/service/client_labels.go
  server/service/client_packs.go
  server/service/client_queries.go
  server/service/handler.go
Labels: Feature: CLI

#1763 Fixes in query, pack and label clients
  server/service/client_labels.go
  server/service/client_packs.go
  server/service/client_queries.go
Labels: Feature: CLI

#1762 Working prototype of fleetctl apply
  cmd/fleetctl/apply.go
  cmd/fleetctl/fleetctl.go
  docs/cli/README.md
  examples/config-many-files/config.yml
  examples/config-many-files/labels.yml
  examples/config-many-files/packs/osquery-monitoring.yml
  examples/config-many-files/queries.yml
  examples/config-single-file.yml
Labels: Feature: CLI

#1766 Implement Get methods for single entities of label, pack and query specs
  server/datastore/datastore_labels_test.go
  server/datastore/datastore_packs_test.go
  server/datastore/datastore_test.go
  server/datastore/mysql/labels.go
  server/datastore/mysql/packs.go
  server/kolide/labels.go
  server/kolide/packs.go
  server/kolide/queries.go
  server/mock/datastore_labels.go
  server/mock/datastore_packs.go
  server/mock/datastore_scheduled_queries.go
  server/service/endpoint_labels.go
  server/service/endpoint_packs.go
  server/service/endpoint_queries.go
  server/service/handler.go
  server/service/service_labels.go
  server/service/service_packs.go
  server/service/service_queries.go
  server/service/transport.go
Labels: Feature: CLI

#1765 Add fleetctl delete command
  cmd/fleetctl/delete.go
  cmd/fleetctl/fleetctl.go
  server/service/client_errors.go
  server/service/client_labels.go
  server/service/client_packs.go
  server/service/client_queries.go
Labels: Feature: CLI

#1764 fleetctl get labels, queries, and packs
  Gopkg.lock
  cmd/fleetctl/fleetctl.go
  cmd/fleetctl/get.go
Labels: Feature: CLI

#1770 Allow `make build` to build fleet and fleetctl
  Makefile
Labels: Component: Development Infrastructure

#1772 Consistent permissions for ~/.fleet/config file
  cmd/fleetctl/config.go
Labels: Feature: CLI

#1768 Add fleetctl get label, pack, query for individual items by name
  cmd/fleetctl/apply.go
  cmd/fleetctl/get.go
  examples/config-many-files/labels.yml
  examples/config-many-files/packs/osquery-monitoring.yml
  examples/config-single-file.yml
  server/kolide/fleetctl.go
  server/service/client_labels.go
  server/service/client_packs.go
  server/service/client_queries.go
Labels: Feature: CLI

#1771 Add interactive login support
  Gopkg.lock
  cmd/fleetctl/login.go
Labels: Feature: Authentication, Feature: CLI

#1774 Add logging middleware for spec endpoints
  server/service/logging_labels.go
  server/service/logging_oquery_options.go
  server/service/logging_packs.go
  server/service/logging_queries.go
Labels: Feature: CLI, Feature: Observability

#1778 Clean up flag descriptions
  cmd/fleetctl/config.go
  cmd/fleetctl/fleetctl.go
  cmd/fleetctl/login.go
  cmd/fleetctl/setup.go
Labels: Feature: CLI

#1776 Improve client error messages with unexpected server errors
  server/service/client_errors.go
  server/service/client_labels.go
  server/service/client_packs.go
  server/service/client_queries.go
  server/service/client_sessions.go
  server/service/client_setup.go
Labels: Feature: CLI, Feature: Observability

#1777 Return 404 errors where appropriate in spec endpoints
  server/datastore/datastore_queries_test.go
  server/datastore/inmem/queries.go
  server/datastore/mysql/labels.go
  server/datastore/mysql/packs.go
  server/datastore/mysql/queries.go
  server/kolide/datastore.go
  server/kolide/queries.go
  server/mock/datastore_queries.go
  server/service/service_queries.go
Labels: Feature: CLI, Feature: Observability

#1787 Update README.md
  README.md
Labels: Needs: Review

#1779 Rename ignore-tls flag to tls-skip-verify
  cmd/fleetctl/api.go
  cmd/fleetctl/config.go
Labels: Feature: CLI

#1797 Fleet 2.0.0 Changlelog
  CHANGELOG.md
  README.md
  cmd/fleetctl/convert.go
  docs/cli/README.md
Labels: Component: Documentation

#1798 Add a setup guide for new CLI users
  cmd/fleetctl/fleetctl.go
  cmd/fleetctl/get.go
  cmd/fleetctl/login.go
  cmd/fleetctl/setup.go
  docs/cli/README.md
  docs/cli/file-format.md
  docs/cli/setup-guide.md
  server/service/client_appconfig.go
Labels: Component: Documentation, Feature: CLI
