Repository kolide/fleet, pull requests merged in 2019-01, with the labels that each got.

#1973 Upgrade Bourbon to 5.1.0 and fix deprecation warnings
  frontend/components/AuthenticationFormWrapper/_styles.scss
  frontend/components/Footer/_styles.scss
  frontend/components/LoginRoutes/_styles.scss
  frontend/components/SmtpWarning/_styles.scss
  frontend/components/StackedWhiteBoxes/_styles.scss
  frontend/components/UserBlock/_styles.scss
  frontend/components/buttons/Button/_styles.scss
  frontend/components/buttons/EllipsisMenu/_styles.scss
  frontend/components/flash_messages/FlashMessage/_styles.scss
  frontend/components/flash_messages/PersistentFlash/_styles.scss
  frontend/components/forms/ChangeEmailForm/_styles.scss
  frontend/components/forms/ChangePasswordForm/_styles.scss
  frontend/components/forms/InviteUserForm/_styles.scss
  frontend/components/forms/LoginForm/_styles.scss
  frontend/components/forms/LogoutForm/_styles.scss
  frontend/components/forms/RegistrationForm/ConfirmationPage/_styles.scss
  frontend/components/forms/RegistrationForm/_styles.scss
  frontend/components/forms/fields/Checkbox/_styles.scss
  frontend/components/forms/fields/Dropdown/_styles.scss
  frontend/components/forms/fields/InputField/_styles.scss
  frontend/components/forms/fields/InputFieldWithIcon/_styles.scss
  frontend/components/forms/fields/SelectTargetsDropdown/TargetOption/_styles.scss
  frontend/components/forms/fields/SelectTargetsDropdown/_styles.scss
  frontend/components/forms/fields/Slider/_styles.scss
  frontend/components/hosts/HostContainer/_styles.scss
  frontend/components/hosts/HostDetails/_styles.scss
  frontend/components/hosts/LonelyHost/_styles.scss
  frontend/components/loaders/ProgressBar/_styles.scss
  frontend/components/loaders/Spinner/_styles.scss
  frontend/components/modals/Modal/_styles.scss
  frontend/components/queries/QueryResultsTable/_styles.scss
  frontend/components/queries/ScheduledQueriesListWrapper/_styles.scss
  frontend/components/side_panels/HostSidePanel/PanelGroupItem/_styles.scss
  frontend/components/side_panels/QuerySidePanel/_styles.scss
  frontend/components/side_panels/SecondarySidePanelContainer/_styles.scss
  frontend/components/side_panels/SiteNavHeader/_styles.scss
  frontend/components/side_panels/SiteNavSidePanel/_styles.scss
  frontend/layouts/CoreLayout/_styles.scss
  frontend/pages/Admin/UserManagementPage/_styles.scss
  frontend/pages/LoginPage/_styles.scss
  frontend/pages/LogoutPage/_styles.scss
  frontend/pages/RegistrationPage/Breadcrumbs/_styles.scss
  frontend/pages/RegistrationPage/_styles.scss
  frontend/pages/UserSettingsPage/_styles.scss
  frontend/pages/hosts/ManageHostsPage/_styles.scss
  frontend/pages/packs/AllPacksPage/_styles.scss
  frontend/pages/packs/EditPackPage/_styles.scss
  frontend/pages/queries/ManageQueriesPage/_styles.scss
  frontend/pages/queries/QueryPage/_styles.scss
  frontend/styles/global/_forms.scss
  frontend/styles/global/_global.scss
  package.json
  postcss.config.js
  webpack.config.js
  yarn.lock
Labels: Component: Frontend

#1982 Add documentation on server_tls_compatibility flag
  docs/infrastructure/configuring-the-fleet-binary.md
Labels: Component: Documentation

#1985 Clarify platform overrides in fleetctl docs
  docs/cli/file-format.md
Labels: Component: Documentation

#1988 Add Support for SMTP LOGIN Authentication Method
  frontend/components/forms/admin/AppConfigForm/AppConfigForm.jsx
  server/kolide/app.go
  server/mail/mail.go
  server/service/service_appconfig.go
Labels: Feature: Authentication, Feature: Settings

#1983 Upgrade React to version 16
  frontend/.test.setup.js
  frontend/components/UserBlock/UserBlock.tests.jsx
  frontend/components/buttons/DropdownButton/DropdownButton.tests.jsx
  frontend/components/forms/ChangePasswordForm/ChangePasswordForm.tests.jsx
  frontend/components/forms/ConfigurePackQueryForm/ConfigurePackQueryForm.tests.jsx
  frontend/components/forms/RegistrationForm/KolideDetails/KolideDetails.tests.jsx
  frontend/components/forms/RegistrationForm/OrgDetails/OrgDetails.tests.jsx
  frontend/components/forms/admin/AppConfigForm/AppConfigForm.tests.jsx
  frontend/components/forms/fields/SelectTargetsDropdown/SelectTargetsDropdown.tests.jsx
  frontend/components/forms/fields/SelectTargetsDropdown/TargetDetails/TargetDetails.tests.jsx
  frontend/components/forms/fields/SelectTargetsDropdown/TargetOption/TargetOption.jsx
  frontend/components/forms/fields/SelectTargetsDropdown/TargetOption/TargetOption.tests.jsx
  frontend/components/forms/queries/QueryForm/QueryForm.jsx
  frontend/components/forms/queries/QueryForm/QueryForm.tests.jsx
  frontend/components/hosts/AddHostModal/AddHostModal.tests.jsx
  frontend/components/packs/PacksList/PacksList.tests.jsx
  frontend/components/packs/PacksList/Row/Row.tests.jsx
  frontend/components/queries/QueryProgressDetails/QueryProgressDetails.tests.jsx
  frontend/components/queries/QueryResultsTable/QueryResultsTable.tests.jsx
  frontend/components/queries/ScheduledQueriesListWrapper/ScheduledQueriesListWrapper.tests.jsx
  frontend/components/side_panels/QuerySidePanel/QuerySidePanel.tests.jsx
  frontend/pages/Admin/AppSettingsPage/AppSettingsPage.tests.jsx
  frontend/pages/Admin/UserManagementPage/UserManagementPage.tests.jsx
  frontend/pages/RegistrationPage/RegistrationPage.tests.jsx
  frontend/pages/UserSettingsPage/UserSettingsPage.tests.jsx
  frontend/pages/hosts/ManageHostsPage/ManageHostsPage.tests.jsx
  frontend/pages/packs/AllPacksPage/AllPacksPage.tests.jsx
  frontend/pages/packs/EditPackPage/EditPackPage.tests.jsx
  frontend/pages/queries/ManageQueriesPage/ManageQueriesPage.tests.jsx
  frontend/pages/queries/QueryPage/QueryPage.tests.jsx
  frontend/test/helpers.jsx
  frontend/test/loaderMock.js
  frontend/test/target_mock.js
  package.json
  yarn.lock
Labels: Component: Frontend, Component: Technical Debt

#1989 Add --timeout flag to fleetctl query
  cmd/fleetctl/query.go
Labels: Feature: CLI

#1979 Add query editor support for control-return
  frontend/components/KolideAce/KolideAce.jsx
  frontend/components/forms/queries/QueryForm/QueryForm.jsx
  frontend/components/queries/QueryPageSelectTargets/QueryPageSelectTargets.jsx
  frontend/components/queries/QueryProgressDetails/QueryProgressDetails.jsx
  frontend/components/queries/QueryProgressDetails/QueryProgressDetails.tests.jsx
  frontend/components/queries/QueryResultsTable/QueryResultsTable.jsx
  frontend/pages/queries/QueryPage/QueryPage.jsx
  frontend/test/helpers.jsx
Labels: Component: Frontend

#1991 Add documentation on OWASP Top 10
  docs/infrastructure/README.md
  docs/infrastructure/owasp-top-10.md
Labels: Component: Documentation, Component: Security

#1995 Default scheduled query name if not specified
  server/datastore/datastore_packs_test.go
  server/datastore/datastore_test.go
  server/datastore/mysql/packs.go
Labels: Bug, Feature: CLI
