Repository kolide/fleet, pull requests merged in 2019-11, with the labels that each got.

#2144 Update query scheduling FAQ
  docs/infrastructure/faq.md
Labels: Component: Documentation, Feature: Packs

#2148 Upgrade lodash to 4.17.15 for security vulnerability
  package.json
  yarn.lock
Labels: Component: Frontend, dependencies

#2121 Allow host expiry window to be altered
  server/datastore/mysql/app_configs.go
Labels: Feature: Enrollment, Feature: Settings

#2149 Update changelog for 2.4.0 release
  CHANGELOG.md
Labels: Component: Documentation

#2150 Update Makefile to tag and push version to Docker
  Makefile
Labels: Component: Development Infrastructure

#2151 Document release process
  docs/development/README.md
  docs/development/release.md
Labels: Component: Documentation

#2152 Default osquery container version to latest in test docker-compose
  tools/osquery/.env
  tools/osquery/README.md
Labels: Component: Development Infrastructure
