Repository kolide/fleet, pull requests merged in 2020-01, with the labels that each got.

#2176 Fix error initializing Fleet when MySQL EVENT permissions missing
  server/datastore/mysql/app_configs.go
Labels: Bug, Component: Databases

#2177 Update goxmldsig dependency
  go.mod
  go.sum
  server/sso/settings_test.go
  server/sso/validate.go
Labels: dependencies

#2181 Fix bugs in error handling for creation of live queries
  server/service/endpoint_campaigns.go
  server/service/logging_campaigns.go
Labels: Bug, Feature: Queries

#2183 Add deprecation warning for "old" TLS compatibility
  docs/infrastructure/configuring-the-fleet-binary.md
  server/config/config.go
Labels: Component: Security

#2185 Adding queryName flag to fleetctl
  cmd/fleetctl/query.go
Labels: Feature: CLI, Feature: Queries

#2182 Allow CREATE in queries from web UI
  frontend/components/forms/validators/validate_query/index.js
  frontend/components/forms/validators/validate_query/validate_query.tests.js
Labels: Component: Frontend, Feature: Queries

#2186 Implement fleetctl goquery
  cmd/fleetctl/fleetctl.go
  cmd/fleetctl/goquery.go
  docs/cli/README.md
  go.mod
  go.sum
  server/datastore/mysql/hosts.go
  server/datastore/mysql/labels.go
  server/service/client_targets.go
Labels: Feature: CLI

#2189 Update changelog for 2.5.0 release.
  CHANGELOG.md
Labels: Component: Documentation
